### Models for Car Prices

In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import OneHotEncoder, PolynomialFeatures
from sklearn.pipeline import Pipeline

In [19]:
ls

data/                               regression_review.ipynb
images/                             transformers-starter.ipynb
linear-regression-sacramento.ipynb


In [20]:
pwd

'/Users/jacobkoehler/Desktop/present/DAT-02-14/ClassMaterial/Unit2/Class8'

In [21]:
#load the cars data
cars = pd.read_csv('data/mtcars.csv', index_col = 0)
cars.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

                   carb  
Mazda RX4             4  
Mazda RX4 Wag         4  
Datsun 710            1  
Hornet 4 Drive        1  
Hornet Sportabout     2

In [22]:
#mpg vs. hp -- X and y (X as DataFrame)
X = cars[['mpg']]
y = cars['hp']

In [23]:
#Linear model instantiate
lr = LinearRegression()

In [24]:
#cross validate with neg_mean_squared_error as scorer
cross_val_score(lr, X, y, cv = 5, scoring='neg_mean_squared_error')

array([-1488.37123279, -1158.31066907, -2477.86137832, -1166.38301226,
       -6395.24822953])

In [26]:
#add a quadratic feature
X['mpg^2'] = cars['mpg']**2
X.head()

<ipython-input-26-9268b9f689b7>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['mpg^2'] = cars['mpg']**2


mpg   mpg^2
Mazda RX4          21.0  441.00
Mazda RX4 Wag      21.0  441.00
Datsun 710         22.8  519.84
Hornet 4 Drive     21.4  457.96
Hornet Sportabout  18.7  349.69

In [27]:
#cross validate linear model
cross_val_score(lr, X, y, cv = 5, scoring = 'neg_mean_squared_error')

array([-1017.45026951,  -754.50829529, -8854.77987111, -1005.40693089,
       -6247.55292699])

In [28]:
import statsmodels.api as sm

In [29]:
model = sm.OLS(y, X).fit()

In [30]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                     hp   R-squared (uncentered):                   0.871
Model:                            OLS   Adj. R-squared (uncentered):              0.862
Method:                 Least Squares   F-statistic:                              101.3
Date:                Wed, 09 Mar 2022   Prob (F-statistic):                    4.55e-14
Time:                        19:27:18   Log-Likelihood:                         -175.33
No. Observations:                  32   AIC:                                      354.7
Df Residuals:                      30   BIC:                                      357.6
Df Model:                           2                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
mpg           20.7703      1.952     10.640      0.000      16.783      24.757
mpg^2         -0.6251      0.080     -7.829      0.000      -0.788      -0.462
==============================================================================
Omnibus:                        3.335   Durbin-Watson:                   1.756
Prob(Omnibus):                  0.189   Jarque-Bera (JB):                2.797
Skew:                           0.718   Prob(JB):                        0.247
Kurtosis:                       2.813   Cond. No.                         94.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [9]:
#Which is better???


In [10]:
#plot histograms of residuals


### `PolynomialFeatures`

Redo the above the `scikitlearn` way.

In [32]:
#train and test split
X_train, X_test, y_train, y_test = train_test_split(cars[['mpg']], cars['hp'], random_state = 42)
X_train.head()

mpg
Merc 450SL         17.3
Mazda RX4          21.0
Hornet Sportabout  18.7
Chrysler Imperial  14.7
Valiant            18.1

In [38]:
#instantiate
poly_features = PolynomialFeatures(degree = 2, include_bias=False)

In [40]:
#fit and transform train
X_train_quad = poly_features.fit_transform(X_train)

In [41]:
#transform test
X_test_quad = poly_features.transform(X_test)
X_test_quad

array([[  19.7 ,  388.09],
       [  10.4 ,  108.16],
       [  19.2 ,  368.64],
       [  32.4 , 1049.76],
       [  22.8 ,  519.84],
       [  19.2 ,  368.64],
       [  15.  ,  225.  ],
       [  27.3 ,  745.29]])

In [42]:
#fit the model
quad = LinearRegression().fit(X_train_quad, y_train)

In [44]:
#make predictions
quad.predict(X_test_quad)

array([131.23560303, 264.76071571, 136.54489949,  67.60639551,
       103.05962838, 136.54489949, 189.53012563,  76.68992407])

In [45]:
from sklearn.metrics import mean_squared_error

In [47]:
mean_squared_error(quad.predict(X_test_quad), y_test, squared = False)

58.520303388705614

In [48]:
cars.head(2)

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110   3.9  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4     4

In [49]:
X2 = cars[['mpg', 'disp']]


In [52]:
import sklearn

In [53]:
sklearn.__version__

'1.0'

In [ ]:
poly_features.get_feature_names

In [54]:
pd.DataFrame(poly_features.fit_transform(X2), columns = poly_features.get_feature_names_out()).head()

mpg   disp   mpg^2  mpg disp    disp^2
0  21.0  160.0  441.00    3360.0   25600.0
1  21.0  160.0  441.00    3360.0   25600.0
2  22.8  108.0  519.84    2462.4   11664.0
3  21.4  258.0  457.96    5521.2   66564.0
4  18.7  360.0  349.69    6732.0  129600.0

### Using a `Pipeline`

Combine transformer with preprocessing.

In [61]:
from sklearn.pipeline import Pipeline

In [62]:
from sklearn import set_config
set_config('diagram')

In [63]:
poly_features = PolynomialFeatures()
X_train_polyfeatures = poly_features.fit_transform(X_train)
X_test_polyfeatures = poly_features.transform(X_test)

In [37]:
quad_reg_nopipe = LinearRegression().fit(X_train_polyfeatures, y_train)
quad_red_nopipe_preds = quad_reg_nopipe.predict(X_test_polyfeatures)

In [38]:
#pipeline to poly then regressor
quad_pipe = Pipeline([('polynomial_features', PolynomialFeatures(include_bias=False)),
                     ('regressor', LinearRegression())])

In [39]:
quad_pipe

Pipeline(steps=[('polynomial_features', PolynomialFeatures(include_bias=False)),
                ('regressor', LinearRegression())])

In [58]:
#cross validate the pipeline
cross_val_score(quad_pipe, X_train, y_train, scoring = 'neg_mean_squared_error')

array([-1038.73412944,  -335.21266277, -1428.57434733,  -926.28033774,
       -4783.35272794])

In [59]:
#evaluate on test
quad_pipe.fit(X_train, y_train)
preds = quad_pipe.predict(X_test)
mean_squared_error(y_test, preds)

3424.62590870615