In [5]:
a = 21

In [1]:
import pandas as pd
import numpy as np

In [2]:
# SHIFT + ENTER
print("Hi")

Hi


In [3]:
a = 14

In [4]:
a

14

In [6]:
a

21

### This is an H3 Heading

 - bullet
 - second bullet
 - third bullet

In [9]:
var = np.arange(20).reshape(5, 4)

In [10]:
var

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [11]:
var.sum()

190

In [12]:
# axis 0 means apply the operation to all the columns
var.sum(axis = 0)

array([40, 45, 50, 55])

In [13]:
var.sum(axis = 1)

array([ 6, 22, 38, 54, 70])